/**
 * ACTION TYPES
 *
 */

export const GET_PLANETS_REQUEST = 'GET_PLANETS_REQUEST';
export const GET_PLANETS_SUCCESS = 'GET_PLANETS_SUCCESS';
export const GET_PLANETS_FAILURE = 'GET_PLANETS_FAILURE';

export const GET_PLANETS_REFRESH_REQUEST = 'GET_PLANETS_REFRESH_REQUEST';
export const GET_PLANETS_REFRESH_SUCCESS = 'GET_PLANETS_REFRESH_SUCCESS';
export const GET_PLANETS_REFRESH_FAILURE = 'GET_PLANETS_REFRESH_FAILURE';



export const GET_DETAIL_REQUEST = 'GET_DETAIL_REQUEST';
export const GET_DETAIL_SUCCESS = 'GET_DETAIL_SUCCESS';
export const GET_DETAIL_FAILURE = 'GET_DETAIL_FAILURE';
